export enum Feature {
  heading = 'heading',
  bold = 'bold',
  italic = 'italic',
  underline = 'underline',
  strike = 'strike',
  dot = 'dot',
  lineSolid = 'lineSolid',
  lineDashed = 'lineDashed',
  textColor = 'textColor',
  backgroundColor = 'backgroundColor',
  alignLeft = 'alignLeft',
  alignCenter = 'alignCenter',
  alignRight = 'alignRight',
  table = 'table',
  formula = 'formula',
  imgupload = 'imgupload',
  insertQs = 'insertQs',
  save = 'save',
}
